version: '3.1'

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - "web"
    volumes:
      - ./static/:/code/static/
      - ./media/:/code/media/

  db:
    image: postgres
    volumes:
      - ./pgdb:/var/lib/postgresql
    ports: 
      - 5432:5432
    restart: always
    env_file: .env

  web:
    container_name: food_stories
    build: .
    ports: 
      - 8000:8000
    depends_on: 
      - "db"
      - "redis"
    env_file: .env

  redis:
    image: redis
    ports: 
      - 6379:6379
    restart: always
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080