# Generated by Django 4.1.1 on 2022-09-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Adiniz')),
                ('email', models.EmailField(max_length=30, verbose_name='E-poct')),
                ('subject', models.CharField(max_length=255, verbose_name='Movzu')),
                ('message', models.TextField(verbose_name='Mesaj')),
            ],
        ),
    ]
