# Generated by Django 4.1.1 on 2023-01-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsciber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Subcriber',
                'verbose_name_plural': 'Subcribers',
                'ordering': ('created_at',),
            },
        ),
    ]
