# Generated by Django 4.1.1 on 2022-12-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_recipe_description_az_recipe_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='slug', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug_az',
            field=models.SlugField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug_en',
            field=models.SlugField(max_length=150, null=True),
        ), 
    ]
